apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestor-back
  template:
    metadata:
      labels:
        app: gestor-back
    spec:
      containers:
        - name: back
          image: gessyca04/gestor-financeiro-back:v1.0.0
          ports:
            - containerPort: 8000
