apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestor-back
  template:
    metadata:
      labels:
        app: gestor-back
    spec:
      containers:
        - name: back
          image: gessyca04/gestor-back:v1.0.3
          ports:
            - containerPort: 8000
          env:
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_KEY

